[package]
name = "build-tools"
version = "1.0.0"
authors = ["Marco Satti <marcosatti@gmail.com>"]
edition = "2018"

[dependencies]
bindgen = "*"
serde = { version = "*" , features = ["derive"] }
serde_json = "*"
