version: 2.1
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - run:
          name: Apt setup
          command: |
            echo "deb http://www.deb-multimedia.org stretch main" >> /etc/apt/sources.list
            apt-get update -oAcquire::AllowInsecureRepositories=true
            apt-get -y install deb-multimedia-keyring
      - run:
          name: OpenAL (openal-soft)
          command: |
            apt-get -y install libopenal-dev
      - run:
          name: OpenGL (mesa)
          command: |
            apt-get -y install mesa-common-dev
      - run:
          name: libmirage
          command: |
            apt-get -y install libmirage10 libmirage10-dev
      - run:
          name: SDL2
          command: |
            apt-get -y install libsdl2-dev
      - run:
          name: LLVM & Clang
          command: |
            apt-get -y install llvm-dev libclang-dev clang
      - checkout
      - run:
          name: External setup
          command: |
            mkdir -p external/openal
            mkdir -p external/opengl
            mkdir -p external/libmirage
      - run:
          name: OpenAL bindgen wrapper
          command: |
            cp external-sample/openal/wrapper.h.sample-linux external/openal/wrapper.h
      - run:
          name: OpenGL bindgen wrapper
          command: |
            cp external-sample/opengl/wrapper.h.sample-linux external/opengl/wrapper.h
      - run:
          name: libmirage bindgen wrapper
          command: |
            cp external-sample/libmirage/wrapper.h.sample-linux external/libmirage/wrapper.h
      - run:
          name: Build
          command: cargo build
workflows:
  version: 2
  Main:
    jobs:
      - build
