version: 2.1
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly-slim
    environment:
      CI_PYTHON_BIN_NAME: python3
    steps:
      - run:
          name: APT update
          command: |
            apt update
      - run:
          name: Install Python 3
          command: |
            apt install -y python3
      - checkout
      - run:
          name: Make external directory structure
          command: |
            mkdir -p external/openal
            mkdir -p external/opengl
            mkdir -p external/libmirage
            mkdir -p external/libcdio
      - run:
          name: Copy external build scripts (check-disable)
          command: |
            cp external-sample/check-disable.py external/openal/check.py
            cp external-sample/check-disable.py external/opengl/check.py
            cp external-sample/check-disable.py external/libmirage/check.py
            cp external-sample/check-disable.py external/libcdio/check.py
      - run:
          name: Build
          command: |
            cd libpsx-rs
            cargo build
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
