version: 2.1
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          name: Change directory (libpsx-rs)
          command: |
            cd libpsx-rs
      - run:
          name: Build
          command: cargo build --features ''
workflows:
  version: 2
  Main:
    jobs:
      - build
