version: 2.1
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - run:
          name: APT update
          command: |
            apt update
      - run:
          name: Install Python 3
          command: |
            apt install -y python3
      - run:
          name: Alias Python3
          command: |
            alias python=python3
      - checkout
      - run:
          name: Make external directory structure
          command: |
            mkdir -p external/openal
            mkdir -p external/opengl
            mkdir -p external/libmirage
      - run:
          name: Copy external build scripts (build-disable)
          command: |
            cp external-sample/build-disable.py external/openal/build.py
            cp external-sample/build-disable.py external/opengl/build.py
            cp external-sample/build-disable.py external/libmirage/build.py
      - run:
          name: Copy external build scripts (check-disable)
          command: |
            cp external-sample/check-disable.py external/openal/check.py
            cp external-sample/check-disable.py external/opengl/check.py
            cp external-sample/check-disable.py external/libmirage/check.py
      - run:
          name: Change directory (libpsx-rs)
          command: |
            cd libpsx-rs
      - run:
          name: Build
          command: cargo build
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
