[package]
name = "libmirage-sys"
version = "3.2.0"
authors = ["Marco Satti <marcosatti@gmail.com>"]
edition = "2018"

[build-dependencies]
build-macros = { path = "../build-macros" }
bindgen = "0.53"
