[package]
name = "libpsx-rs"
version = "0.1.0"
authors = ["Marco Satti <marcosatti@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.9"
log = "0.4"
ansi_term = "0.12"
euclid = "0.19"
rayon = "1.0"
num-traits = "0.2"
lazy_static = "1.3"
sdl2 = "0.32"
thread-id = "3.3"
opengl-sys = { path = "../opengl-sys" }
openal-sys = { path = "../openal-sys" }
average = "0.9"
fixed-vec-deque = "0.1"
spsc-ringbuffer = { git = "https://github.com/marco9999/spsc-ringbuffer" }
capstone = "0.6"
hashbrown = "0.6"
lru = "0.1"
