[package]
name = "opengl-sys"
version = "3.3.0"
authors = ["Marco Satti <marcosatti@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.42"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0"
