[package]
name = "opengl-sys"
version = "1.0.0"
authors = ["Marco Satti <marcosatti@gmail.com>"]
edition = "2018"

[build-dependencies]
build-tools = { path = "../build-tools" }
gl_generator = { version = "*", features = ["unstable_generator_utils"] }
